### ISSUE TITLE
Arbitrary errors after some time of online (more than hour)

### ISSUE THREAD

**Issue by theoden-dd** [laytya/vQueue#1]
Release: 1.2.4a

Count: 8
Error: Interface\AddOns\vQueue\vQueue.lua:2511: attempt to index field `?' (a nil value)
--------------------------------------------------
Count: 13
Error: Interface\AddOns\vQueue\vQueue.lua:2502: attempt to index field `?' (a nil value)

**Comment by Reubentrapdoor** [comment]
Getting the same error on line 2511 with the latest version, logged in time suggested in the title doesn't seem relevant, I get this a few minutes after logging in.
