### ISSUE TITLE
German language has long words... some changes on interface

### ISSUE THREAD

**Issue by hengstenberg** [laytya/vQueue#12]
German translation is sometimes longer than the English original. So I have made some changes on the interface. This should have no influence on other localisations, perhaps there is only some more space. Amendment should be done on `vQueue.lua`. Let's go.
Greets, Hengstenberg

1. row 353
`vQueueFrame:SetWidth(594)`
changed to
`vQueueFrame:SetWidth(644)`

2. row 416
`vQueueFrame.catList:SetWidth(118)`
changed to
`vQueueFrame.catList:SetWidth(168)`

3. row 899
`vQueueFrame.optionsFrame:SetWidth(200)`
changed to
`vQueueFrame.optionsFrame:SetWidth(300)`

4. row 917
`vQueueFrame.hostlistFindButton:SetPoint("BOTTOMRIGHT", vQueueFrame.optionsFrame, "BOTTOMRIGHT", -65, 20)`
changed to
`vQueueFrame.hostlistFindButton:SetPoint("BOTTOMRIGHT", vQueueFrame.optionsFrame, "BOTTOMRIGHT", -115, 20)`

5. insert after row 1147
`getglobal(vQueueFrame.filterCheckOnlyFilter:GetName() .."Text"):SetFont("Fonts\\FRIZQT__.TTF", 8)`

**Comment by laytya** [comment]
test v1.2.7 commit

**Comment by hengstenberg** [comment]
Your changes for the german localisation are included very elegant! Hengstenberg

**Comment by laytya** [comment]
thx
