### ISSUE TITLE
Fine tuning of spelling

### ISSUE THREAD

**Issue by hengstenberg** [laytya/vQueue#13]
Hi Laytya, I have found some misspelling in `Localization.lua`. Changes are also made to `vQueue.lua`. One of them lead to an error message with the german client. Greets, Hengstenberg

1. **line 49**:
`<-- Select a catergory`
corrected to ("category" shows one "r" too much)
`<-- Select a category`
This must be corrected also in the
- ruRU-localisation in **line 115** and
- deDE-localisation in **line 181**
- `vQueue.lua` in line 1545

2. **line 63**:
`vQueue: So you need join channels manualy or in macro: 1 channel per macro`
corrected to ("manually" was written with only one "l")
`vQueue: So you need join channels manually or in macro: 1 channel per macro`
This must be corrected also in the
- ruRU-localisation in **line 129**
- The deDE-localisation in **line 195** is still correct. This is the reason, why there is a error message with the german client now. When I was doing the translation, I have corrected this point, but I have forgotten to tell you this with the last issue.

**Comment by laytya** [comment]
ok
