### ISSUE TITLE
Missing german acronym for Ragefire chasm 

### ISSUE THREAD

**Issue by hengstenberg** [laytya/vQueue#14]
Yesterday evening I tested new version 1.2.7 and found a common acronym for the dungeon "Ragefire chasm" and "Blackfathom Deeps". Changes due to `vQueueMessages.lua`. Greets, Hengstenberg

line 367:
`table.insert(CATARGS["rfc"], "rf")`
changed to (additonal acronym is "rfa")
```
MergeTables(CATARGS["rfc"],{
	"rf",
	"rfa"
})
```

new line:
`table.insert(CATARGS["bfd"],"bft")`

**Comment by laytya** [comment]
ok
