### ISSUE TITLE
Error on first launch - missing variable

### ISSUE THREAD

**Issue by Cephel** [laytya/vQueue#17]
https://github.com/laytya/vQueue/blob/3a24d72feafc05f550996b4a403a4ab9aeb765be/vQueue.lua#L511

`NAME` is undefined

**Comment by laytya** [comment]
its standard wow client variable... what client's locale do you have?

**Comment by laytya** [comment]
ok will fix it

**Comment by laytya** [comment]
test 1.2.7b
