### ISSUE TITLE
Minimap Button

### ISSUE THREAD

**Issue by phendrome** [laytya/vQueue#20]
Having an addition to remove the minimap button would good as it would clear the clutter of a clean minimap. At the moment it is ugly as hell.

1. Being able to remove the minimap button
2. Adding an option to bind vQueue to open through a keybinding (or adding a command like /vqueue which you could macro)

**Comment by laytya** [comment]
I m using [MinimapButtonFrame](https://github.com/laytya/MinimapButtonFrame-vanilla) to hide all icons.
