### ISSUE TITLE
Sprocket doesn't work anymore when using vQueue

### ISSUE THREAD

**Issue by FrostShock** [laytya/vQueue#21]
I tried this addon, I still have to study it's features but I have a problem with it:

If I load vQueue, my Sprocket addon doesn't work anymore.

  When I try to add a new Menu or when I try to drag a spell on an existing menu ( "Action Bar 1"   -   "Player Frame"   -   "Micro Buttons"), I get this error:

`Error: Interface\AddOns\Sprocket\SprocketClasses.lua:818 AceOO-2.0: Improper self passed to init. You must do MyClass.super.prototype.init(self, ...)`

**Comment by laytya** [comment]
update libs in Sprocket to latest one.

**Comment by FrostShock** [comment]
Excuse me, I tried with two versions of Ace2 and it didn't work:
* https://github.com/laytya/Ace2   -   this one seems to be more fresh but it gives this error "Cannot find a library instance of ItemDef-2.0"
* https://github.com/wow-vanilla-addons/Ace2

Where should I get the Ace2 library from? Can you try vQueue in combination with Sprocket and see if it works?

Thank you.

**Comment by laytya** [comment]
send me link of Sprocket

**Comment by FrostShock** [comment]
https://legacy-wow.com/vanilla-addons/sprocket/

**Comment by laytya** [comment]
Try updated by me version
https://github.com/laytya/Vanilla-Addons/blob/master/Sprocket.zip

**Comment by FrostShock** [comment]
This one works, thanks!
Where did you get the libraries from, do you have a download link?

**Comment by laytya** [comment]
https://github.com/laytya/Libs2
https://github.com/laytya/Ace2
