### ISSUE TITLE
reply

### ISSUE THREAD

**Issue by Artur91425** [laytya/vQueue#3]
Даже если я слишком маленького уровня и не подхожу для выбранной группы в инст, я все равно могу нажать на кнопку reply и отправить сообщение игроку. По идеи, если уровень игрока мал, не должно быть кнопки reply или должна выводиться соответствующая ошибка, что я слишком маленького уровня

**Comment by laytya** [comment]
Это специально оставлено на усмотрение пати лидера. Ты все равно можешь попросится в группу, но взять или нет это дело лидера.
