### ISSUE TITLE
Локаль

### ISSUE THREAD

**Issue by Artur91425** [laytya/vQueue#4]
[vQueue-1.2.4b.zip](https://github.com/laytya/vQueue/files/877168/vQueue-1.2.4b.zip)

Добавил поддержку локали в аддон
Добавил библиотеки Babble-Class-2.2, Babble-Zone-2.2, AceLocale-2.2
Обновил имеющиеся библиотеки, а то они все очень старые были и в AceAddon-2.0 не было ruRU локали 
Также поправил поинты для всех кнопок, чтобы они нормально перемещались относительно друг друга при изменении длины названия на них
Переместил вывод ошибок таких как "(Leave group before queueing for other groups)" или "(Select a role to start finding)" и т.д. в шапку окна аддона над его названием, а то раньше эти сообщения писались поверх кнопок...

Локаль добавлена на только что скаченную версию 1.2.4b. Все перечисленные мною ошибки в сообщениях ниже для нее соответственно тоже актуальны. Проще говоря кроме добавления локали и обновления библиотек я ничего не трогал

**Comment by laytya** [comment]
спасибо, pulled
