### ISSUE TITLE
кнопка миникарты

### ISSUE THREAD

**Issue by Artur91425** [laytya/vQueue#5]
У кнопки миникарты неправильно установлен центр окружности из-за чего она перемещается не по краю миникарты, а со сдвигом.

Также предлагаю удалить кнопку "Close". После добавления кнопки-крестика ее надобность отпадает
И также прошу поправить ру локаль, я там немного накосячил:
"Роль(-и)", замени на "Роль(и)",
"Игрок(и/ов) в вашем списке ожидания.", замени на " игрок(а/ов) в вашем списке ожидания.",

**Comment by laytya** [comment]
вроде это исправлено
