### ISSUE TITLE
Постоянные ошибки

### ISSUE THREAD

**Issue by dakotarisen** [laytya/vQueue#6]
Спамятся после некоторого провождения в игре
![2](https://cloud.githubusercontent.com/assets/25033779/24474990/2db8dc2c-14d7-11e7-99ae-3a17cb53140e.jpg)

**Comment by laytya** [comment]
какие действия с vQueue были перед этим?

**Comment by dakotarisen** [comment]
Искал группу-ответил лидеру группы-приняли-чуть побегал в группе и начались сыпаться ошибки

**Comment by laytya** [comment]
скачай мастер и проверяй

**Comment by dakotarisen** [comment]
Вроде пока все хорошо,а можно ли добавить удаление игроков в списке ожидания,например,спустя 5 мин.?Также было бы хорошо добавить авто повторяющийся крик в ворлд чат о наборе в группу.
