### ISSUE TITLE
Crash at Startup

### ISSUE THREAD

**Issue by JHuenerberg** [laytya/vQueue#8]
![unbenannt](https://user-images.githubusercontent.com/4007444/27970252-737a56bc-634e-11e7-958a-f8271c3a7c13.PNG)

**Comment by laytya** [comment]
try to delete old settings in WTF folder

**Comment by JHuenerberg** [comment]
Does not fix it.

**Comment by laytya** [comment]
can u update addon to latest version and reproduce this bug...
