### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by Aviana** [laytya/vQueue#9]
![error](https://user-images.githubusercontent.com/425023/32699574-34ee7fd0-c7b8-11e7-952d-9e1b5117bc9e.png)

**Comment by laytya** [comment]
I cant reproduce this errors. may be uhave another version of vQueue?

**Comment by xVitali2** [comment]
просто кто-нибудь пишет о приглашении в гильдию, аддон это сообщение цепляет, и потом после 40 сек и\или 5мин постоянно выскакивают ошибки

**Comment by laytya** [comment]
не понятно все равно... как можно это воспроизвести?
